var data = [
  {
      "id": 23182292297,
      "name": "0.51-1KG Winter Outfitters Jacket Windbreaker",
      "price": 12,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 46,
      "liked": false,
      "liked_count": 1,
      "brand": "",
      "shop_location": "Baggao, Cagayan",
      "rating": 4.5,
      "can_use_cod": true
  },
  {
      "id": 24953520015,
      "name": "Women's Winter Plush Coat Long Sleeve Warm Fluffy Plush Jacket",
      "price": 628,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 60000,
      "liked": false,
      "liked_count": 8,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 23600680507,
      "name": "2017 New Winter Warm Faux Fur Fox Coat Jackets Casacos Femininos Long Sleeve Parka Hair Jacket Coat",
      "price": 528,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 23933,
      "liked": false,
      "liked_count": 11,
      "brand": "",
      "shop_location": "Makati City, Metro Manila",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 24156773777,
      "name": "[MD] Women Winter Coat Solid Color Warm Furry Plush Plus Size Lady Coat Winter Clothes",
      "price": 557,
      "status": "normal",
      "currency": "PHP",
      "discount": "41",
      "stock": 419956,
      "liked": false,
      "liked_count": 2,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 23126382989,
      "name": "Women Warm Wool Collar Long Sleeve Jacket Winter Zipper Harajuku Office Lady Coat",
      "price": 548,
      "status": "normal",
      "currency": "PHP",
      "discount": "67",
      "stock": 219584,
      "liked": false,
      "liked_count": 352,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.636363636363637,
      "can_use_cod": true
  },
  {
      "id": 22288797979,
      "name": "{In stock}Men Winter Coat Warm Puffer Jacket Full Zip Stand Collar Pockets Thicken Cotton Coat Warm Casual Work Coat Outerwear",
      "price": 700,
      "status": "normal",
      "currency": "PHP",
      "discount": "46",
      "stock": 199980,
      "liked": false,
      "liked_count": 0,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 19657923960,
      "name": "Men's Winter Down Thermal Jacket Outdoor Fashion Stand Collar Jacket With Thick Thermal Cotton",
      "price": 797,
      "status": "normal",
      "currency": "PHP",
      "discount": "43",
      "stock": 4807,
      "liked": false,
      "liked_count": 202,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.666666666666667,
      "can_use_cod": true
  },
  {
      "id": 22117095219,
      "name": "Winter New Style Double Sided Jacket Loose Hooded",
      "price": 629,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 14890,
      "liked": false,
      "liked_count": 3977,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 14134900073,
      "name": "Jackets Men Soft Shell Techwear Windproof Waterproof Breathable Fleece Thermal Coats",
      "price": 339,
      "status": "normal",
      "currency": "PHP",
      "discount": "12",
      "stock": 408,
      "liked": false,
      "liked_count": 157,
      "brand": "",
      "shop_location": "Valenzuela City, Metro Manila",
      "rating": 4.871794871794871,
      "can_use_cod": true
  },
  {
      "id": 22507727431,
      "name": "Uniqlo Men Standing Collar Warm Winter Coat Windbreaker Outdoors Waterproof Jackets",
      "price": 1199,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 8291,
      "liked": false,
      "liked_count": 866,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.769230769230769,
      "can_use_cod": true
  },
  {
      "id": 25103863509,
      "name": "[SA] Women Fall Winter Overcoat Loose Lapel Thickened Windproof Warm Soft Double-breasted Solid Color Pockets Long Sleeve Lady Mid Length Trench Coat",
      "price": 706,
      "status": "normal",
      "currency": "PHP",
      "discount": "61",
      "stock": 199979,
      "liked": false,
      "liked_count": 3,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 24156773969,
      "name": "[MD] Women Hoodie Plus Size All Match Autumn Winter Solid Color Warm Coat Streetwear",
      "price": 802,
      "status": "normal",
      "currency": "PHP",
      "discount": "37",
      "stock": 119988,
      "liked": false,
      "liked_count": 4,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 2,
      "can_use_cod": true
  },
  {
      "id": 16182083208,
      "name": "Preloved/Thrifted(US/JP)- Winter, Puffer, Down, Parka,Fleece, Fur, Knitted Jackets",
      "price": 385,
      "status": "normal",
      "currency": "PHP",
      "discount": "30",
      "stock": 1,
      "liked": false,
      "liked_count": 102,
      "brand": "",
      "shop_location": "Taytay, Rizal",
      "rating": 4.875,
      "can_use_cod": true
  },
  {
      "id": 22316369631,
      "name": "Men Windbreaker Winter Jacket Outdoors Waterproof Sports Warm Winter Skiing Coat",
      "price": 729,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 7183,
      "liked": false,
      "liked_count": 15,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.2,
      "can_use_cod": true
  },
  {
      "id": 25011836071,
      "name": "[WE] Autumn Winter Cartoon Ears Long Sleeve Keep Warm Lambswool Hooded Jacket For Women AS",
      "price": 497,
      "status": "normal",
      "currency": "PHP",
      "discount": "25",
      "stock": 3,
      "liked": false,
      "liked_count": 1,
      "brand": "",
      "shop_location": "Valenzuela City, Metro Manila",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 23377866328,
      "name": "Womens Zip Up Hoodie Sherpa Lined Fleece Jacket Winter Warm Jackets ",
      "price": 598,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 230,
      "liked": false,
      "liked_count": 33,
      "brand": "",
      "shop_location": "Las Pinas City, Metro Manila",
      "rating": 4.6,
      "can_use_cod": true
  },
  {
      "id": 25752174620,
      "name": "Women Down Coat Women Puffer Coat Stylish Winter Hooded Jacket for Women Warm and Trendy Outerwear for Cold Weather All-match Streetwear Coat",
      "price": 682,
      "status": "normal",
      "currency": "PHP",
      "discount": "57",
      "stock": 149972,
      "liked": false,
      "liked_count": 22,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 21052281046,
      "name": "Autumn and Winter New Cold Casual Men's Cotton Jacket Windproof Jacket",
      "price": 726,
      "status": "normal",
      "currency": "PHP",
      "discount": "25",
      "stock": 29849,
      "liked": false,
      "liked_count": 9,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.2,
      "can_use_cod": true
  },
  {
      "id": 15397388355,
      "name": "[OTT] Winter Men Jacket Plaid Buttoned Coldproof Loose Plush Lining Hooded Jacket Outwear for Outdoor",
      "price": 859,
      "status": "normal",
      "currency": "PHP",
      "discount": "39",
      "stock": 199980,
      "liked": false,
      "liked_count": 12,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.714285714285714,
      "can_use_cod": true
  },
  {
      "id": 18532488655,
      "name": "Autumn Winter Jacket Men's Windbreaker Hooded Warm Coat Outdoors Sports Jackets",
      "price": 869,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 5511,
      "liked": false,
      "liked_count": 78,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.7,
      "can_use_cod": true
  },
  {
      "id": 19526004958,
      "name": "Padded Men's Plus Velvet Thickened Lamb Velvet Winter Coat New Cotton Windproof Warm Cotton",
      "price": 1299,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 16744,
      "liked": false,
      "liked_count": 111,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.818181818181818,
      "can_use_cod": true
  },
  {
      "id": 25200308483,
      "name": "The North Face M-8xl New High-End Executive Cotton-Padded Jacket For Men Middle-Aged And Elderly Men's Jacket With Cotton Thickened Warm Standing Collar Casual Cotton-Padded Jacket",
      "price": 1199,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 17967,
      "liked": false,
      "liked_count": 29,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.714285714285714,
      "can_use_cod": true
  },
  {
      "id": 20566594347,
      "name": "Unisex Long Sleeve Hooded Nazgul Long Coat Zipper Closure Fleece Lined fashionable warm men women long hooded Zipper Closure Hooded Nazgul Long Coat",
      "price": 570,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 11200,
      "liked": false,
      "liked_count": 30,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.333333333333333,
      "can_use_cod": true
  },
  {
      "id": 23960693604,
      "name": "Winter Padded Coats Cotton Jackets  Thick Warm Hooded Quilt Snow Outwear",
      "price": 570,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 47662,
      "liked": false,
      "liked_count": 51,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.592592592592593,
      "can_use_cod": true
  },
  {
      "id": 20246739449,
      "name": "ã€wmã€‘Business Jacket Long Sleeve Skin-friendly Streetwear Slim Fit Lapel Warm Men Coat for Office",
      "price": 585,
      "status": "normal",
      "currency": "PHP",
      "discount": "29",
      "stock": 149985,
      "liked": false,
      "liked_count": 9,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 2.6666666666666665,
      "can_use_cod": true
  },
  {
      "id": 25256280273,
      "name": "The NORTH FACE 2024 New Style Men's Down Jacket Jacket Jacket Brand Sports Fashion Winter Warm Coat Jacket",
      "price": 1099,
      "status": "normal",
      "currency": "PHP",
      "discount": "45",
      "stock": 186878,
      "liked": false,
      "liked_count": 0,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 23984930292,
      "name": "CFW_ Men Winter Coat Padded Thick Solid Color Zipper Closure Stand Collar Long Sleeve Windproof Soft Warm Cold Resistant Men Jacket",
      "price": 655,
      "status": "normal",
      "currency": "PHP",
      "discount": "63",
      "stock": 279972,
      "liked": false,
      "liked_count": 9,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.666666666666667,
      "can_use_cod": true
  },
  {
      "id": 18676560845,
      "name": "Plus Size M-7XL Men's Hooded Jacket Windproof Oversize Casual Jacket Outdoor Sports Fashion Coat Warm and Waterproof",
      "price": 901,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 2650,
      "liked": false,
      "liked_count": 65,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.4,
      "can_use_cod": true
  },
  {
      "id": 20094369618,
      "name": "Puffer Jackets/Wind Breaker Jackets/Fashion Jackets;Coats/Bomber/Winter Jackets (NEW ARRIVAL)",
      "price": 200,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 48,
      "liked": false,
      "liked_count": 85,
      "brand": "",
      "shop_location": "Baguio City, Benguet",
      "rating": 4.777777777777778,
      "can_use_cod": true
  },
  {
      "id": 22317826871,
      "name": "Hot Sale Â· Men Winter Light Blue Lamb Fleece Denim Jacket Thickened Casual Slim-Fit Top",
      "price": 1122,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 20909,
      "liked": false,
      "liked_count": 89,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.461538461538462,
      "can_use_cod": true
  },
  {
      "id": 22387296818,
      "name": "GRE Cold Weather Women Coat Women Thermal Jacket Stylish Winter Hooded Jacket for Women Warm and Trendy Outerwear for Cold Weather All-match Streetwear Coat",
      "price": 698,
      "status": "normal",
      "currency": "PHP",
      "discount": "57",
      "stock": 149985,
      "liked": false,
      "liked_count": 1,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 19494918401,
      "name": "Men's Padded Coat Mid-Length Thick Down Jacket Winter Warm Coat Fitted Fit",
      "price": 590,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 39200,
      "liked": false,
      "liked_count": 3,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 22666367292,
      "name": "Men's Classic PU Leather Jacket Warm Full Zip Outwear Biker Jacket",
      "price": 897,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 33297,
      "liked": false,
      "liked_count": 2,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 3,
      "can_use_cod": true
  },
  {
      "id": 13097345016,
      "name": "Uniqlo Women's Winter Warm Jacket Windbreaker Jacket Wool Fleece Jacket",
      "price": 699,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 12534,
      "liked": false,
      "liked_count": 182,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.214285714285714,
      "can_use_cod": true
  },
  {
      "id": 10283243422,
      "name": "Lamb Wool Denim Jacket S-3XL Lamb Wool Thermal Jacket Overalls Jacket Autumn Winter Denim Jacket All-Match Denim Jacket",
      "price": 1310,
      "status": "normal",
      "currency": "PHP",
      "discount": "32",
      "stock": 10418,
      "liked": false,
      "liked_count": 503,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.7073170731707314,
      "can_use_cod": true
  },
  {
      "id": 10456942653,
      "name": "New winter coatâœ¼â˜’â£Polar fleece men s coat cotton winter new style Korean style trendy lamb wool warm coat short lamb wool coat",
      "price": 656,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 2768,
      "liked": false,
      "liked_count": 576,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.424242424242424,
      "can_use_cod": true
  },
  {
      "id": 22782827674,
      "name": "Autumn and winter retro color matching corduroy jacket with trendy embroidery and versatile warm bomber jacket suitable for men and women",
      "price": 800,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 7999,
      "liked": false,
      "liked_count": 5,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 0,
      "can_use_cod": true
  },
  {
      "id": 3661878957,
      "name": "Bomber jacket Cargo jacket Unisex Winter Jacket Coat",
      "price": 479,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 4472,
      "liked": false,
      "liked_count": 7,
      "brand": "No Brand",
      "shop_location": "Paranaque City, Metro Manila",
      "rating": 3.888888888888889,
      "can_use_cod": false
  },
  {
      "id": 23581408045,
      "name": "[WY] M-4xl Ready Stock Lamb Wool Jacket Fleece Lining Thickened Zipper Cardigan Casual Loose Large Size Hooded Ladies Top Autumn Winter All @",
      "price": 595,
      "status": "normal",
      "currency": "PHP",
      "discount": "13",
      "stock": 23931,
      "liked": false,
      "liked_count": 68,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.857142857142857,
      "can_use_cod": true
  },
  {
      "id": 20883094460,
      "name": "2023 Fashion Autumn Winter Coat Women's Jacket Fleece Furry Warm Short Jacket Coat Zipper Coat",
      "price": 493,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 17380,
      "liked": false,
      "liked_count": 156,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.705882352941177,
      "can_use_cod": true
  },
  {
      "id": 21064709057,
      "name": "Adidas Winter Cotton Jacket Men's Outdoor Warm Hooded Loose Camouflage Coat",
      "price": 1377,
      "status": "normal",
      "currency": "PHP",
      "discount": "47",
      "stock": 6800,
      "liked": false,
      "liked_count": 194,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.779220779220779,
      "can_use_cod": true
  },
  {
      "id": 22332370971,
      "name": "Casual Solid Color Men's Long Sleeve Overcoat Fashion Winter Buttons Pockets Men's Long Coats Double-breasted Thin Warm Coats",
      "price": 1083,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 10800,
      "liked": false,
      "liked_count": 183,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.461538461538462,
      "can_use_cod": true
  },
  {
      "id": 22451588793,
      "name": "High Quality New Men's Down Jacket Stand Collar Winter Warm Jacket",
      "price": 127,
      "status": "normal",
      "currency": "PHP",
      "discount": "60",
      "stock": 17077,
      "liked": false,
      "liked_count": 8,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.166666666666667,
      "can_use_cod": true
  },
  {
      "id": 21782760737,
      "name": "Men's Casual Trench Coat Winter Long Jacket Double Breasted",
      "price": 920,
      "status": "normal",
      "currency": "PHP",
      "discount": "57",
      "stock": 23384,
      "liked": false,
      "liked_count": 76,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.2727272727272725,
      "can_use_cod": true
  },
  {
      "id": 15688009350,
      "name": "Fashion Parka Women Coat Plus Size Long Sleeve Thick Warm Clothes 2022 Autumn Winter New Cotton",
      "price": 815,
      "status": "normal",
      "currency": "PHP",
      "discount": "67",
      "stock": 73824,
      "liked": false,
      "liked_count": 1655,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.840579710144928,
      "can_use_cod": true
  },
  {
      "id": 16282014294,
      "name": "[M-5XL] Uniqlo Fleece Jacket 2022 New Warm and Wear-resistant Stand Collar Sports Windbreaker",
      "price": 699,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 3616,
      "liked": false,
      "liked_count": 444,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.625,
      "can_use_cod": true
  },
  {
      "id": 24411212115,
      "name": "Puffer/Bubble Jackets/Coats/Parka;Winter Jackets;Fashion/Mixed Jackets(NEW ARRIVAL)",
      "price": 149,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 34,
      "liked": false,
      "liked_count": 23,
      "brand": "",
      "shop_location": "Baguio City, Benguet",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 21624605769,
      "name": "TRENCH COAT LADIES TRENDY CHIC 2022 FASHION WOOL WINTER JACKET",
      "price": 99,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 1,
      "liked": false,
      "liked_count": 149,
      "brand": "",
      "shop_location": "Marikina City, Metro Manila",
      "rating": 4.591836734693878,
      "can_use_cod": true
  },
  {
      "id": 21075883123,
      "name": "Women Warm Wool Collar Long Sleeve Jacket Winter Zipper Harajuku Office Lady Coat",
      "price": 228,
      "status": "normal",
      "currency": "PHP",
      "discount": "68",
      "stock": 120791,
      "liked": false,
      "liked_count": 23,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4,
      "can_use_cod": true
  },
  {
      "id": 22775987015,
      "name": "ã€S-3XLã€‘2023 Autumn And Winter New High-End Trend Casual Lapel Thickened Short Solid Color Woolen Jacket For Men",
      "price": 539,
      "status": "normal",
      "currency": "PHP",
      "discount": "31",
      "stock": 27944,
      "liked": false,
      "liked_count": 56,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 22541864452,
      "name": "M-5XL Fleece Thickened Men's Winter Jacket Lamb Fleece Warm Windproof Jacket Cold and Hot Jacket Long-sleeved High-quality Jacket",
      "price": 1047,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 2777,
      "liked": false,
      "liked_count": 20,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 20582000862,
      "name": "Uniqlo Women Waterproof Hooded Jackets Outdoors Fashion Hiking High Quality Warm Windproof Coat",
      "price": 888,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 7463,
      "liked": false,
      "liked_count": 65,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.833333333333333,
      "can_use_cod": true
  },
  {
      "id": 11582173004,
      "name": "Men Jacket Green Soft Shell Tactical Techwear Windproof Breathable Fleece Hooded Coats",
      "price": 739,
      "status": "normal",
      "currency": "PHP",
      "discount": "7",
      "stock": 328,
      "liked": false,
      "liked_count": 106,
      "brand": "",
      "shop_location": "Valenzuela City, Metro Manila",
      "rating": 4.6,
      "can_use_cod": false
  },
  {
      "id": 18492837869,
      "name": "Uniqlo Cotton Jacket Men's 2023 New Padded Jacket Winter Jacket Men's Thick Coat",
      "price": 1259,
      "status": "normal",
      "currency": "PHP",
      "discount": "30",
      "stock": 11893,
      "liked": false,
      "liked_count": 232,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.703703703703703,
      "can_use_cod": true
  },
  {
      "id": 23652632686,
      "name": "Uniqlo Men'S Warm Youth Loose Fit Stand-Up Collar Cold Warm Cotton Jacket",
      "price": 1199,
      "status": "normal",
      "currency": "PHP",
      "discount": "25",
      "stock": 15924,
      "liked": false,
      "liked_count": 97,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 4.909090909090909,
      "can_use_cod": true
  },
  {
      "id": 22018751188,
      "name": "Preloved and ukay puffer jacket and winter  long coat for women",
      "price": 160,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 8,
      "liked": false,
      "liked_count": 87,
      "brand": "",
      "shop_location": "Taguig City, Metro Manila",
      "rating": 4.833333333333333,
      "can_use_cod": true
  },
  {
      "id": 20292345980,
      "name": "The North Face Men Windbreaker Sports Jackets Winter Warm Coat",
      "price": 699,
      "status": "normal",
      "currency": "PHP",
      "discount": "50",
      "stock": 7843,
      "liked": false,
      "liked_count": 40,
      "brand": "",
      "shop_location": "Mainland China",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 19132487577,
      "name": "IWR0188 - BENCH/ Men's Winter Jacket",
      "price": 1699,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 15,
      "liked": false,
      "liked_count": 61,
      "brand": "",
      "shop_location": "Calamba City, Laguna",
      "rating": 5,
      "can_use_cod": true
  },
  {
      "id": 4750899749,
      "name": "bomber jacket/ cargo jacket/ unisex winter jacket coat",
      "price": 479,
      "status": "normal",
      "currency": "PHP",
      "discount": null,
      "stock": 1315,
      "liked": false,
      "liked_count": 9,
      "brand": "No Brand",
      "shop_location": "Paranaque City, Metro Manila",
      "rating": 3.75,
      "can_use_cod": false
  },
  {
      "id": 19609087160,
      "name": "ï¼ˆShips within 48 hoursï¼‰Thermal Jacket With Hood Plush Colored Mixed Casual Artificial Fur Zipper",
      "price": 618,
      "status": "normal",
      "currency": "PHP",
      "discount": "67",
      "stock": 52443,
      "liked": false,
      "liked_count": 1700,
      "brand": "No Brand",
      "shop_location": "Mainland China",
      "rating": 4.732782369146006,
      "can_use_cod": true
  }
]